; Paths are relative to this settings file:

backend_python_version = 3.12.10
backend_python_finish_installation_relative_path = ..\scripts\setup\finish_backend_installation.py
; UPDATE contents of .gitignore + pyproject.toml on change:
backend_python_install_dir_relative_path = ..\backend_python
