backend_python_version = 3.12.10
; Relative to this settings file:
backend_python_finish_installation_relative_path = scripts\setup\finish_backend_installation.py
; No path allowed, only folder mame. UPDATE contents of.gitignore + pyproject.toml on change:
backend_python_install_dir_name = backend_python
