@echo off
setlocal

rem ==========================
rem benchmark settings

set "HERE=%~dp0"
set "CODE_DIR=%HERE%..\.."
set "BENCHMARK_PY=%HERE%helper_scripts\measure_startup_time.py"
se t "VENV_PY=%HERE%..\..\py_env\virt_env\Portable_Scripts\python.bat"
se t "DIST_PY=%HERE%..\..\py_env\py_dist\python.exe"

set "RUNS=10"
set "TIMEOUT_SECONDS=5"
set "RUN_SETUP_WARMUP=1"
set "SETUP_TIMEOUT_SECONDS=600"

rem 1 = measure, 0 = skip
set "MEASURE_WINDOWS_TERMINAL_SHORTCUT=1"
set "MEASURE_NO_TERMINAL_SHORTCUT=1"
set "MEASURE_TERMINAL_EMULATOR_SHORTCUT=1"
set "MEASURE_BROWSER_SHORTCUT=1"
set "MEASURE_DIRECT_PY_DIST=1"
set "MEASURE_DIRECT_GLOBAL_PY=1"
set "MEASURE_DIRECT_START_PROGRAM=1"

rem ==========================

set "BENCHMARK_ARGS= %RUNS% %TIMEOUT_SECONDS%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_WINDOWS_TERMINAL_SHORTCUT%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_NO_TERMINAL_SHORTCUT%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_TERMINAL_EMULATOR_SHORTCUT%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_BROWSER_SHORTCUT%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_DIRECT_PY_DIST%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_DIRECT_GLOBAL_PY%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %RUN_SETUP_WARMUP%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %SETUP_TIMEOUT_SECONDS%"
set "BENCHMARK_ARGS=%BENCHMARK_ARGS% %MEASURE_DIRECT_START_PROGRAM%"

if exist "%VENV_PY%" (
    call "%VENV_PY%" "%BENCHMARK_PY%" %BENCHMARK_ARGS% %*
    set "EXIT_CODE=%ERRORLEVEL%"
) else if exist "%DIST_PY%" (
    "%DIST_PY%" "%BENCHMARK_PY%" %BENCHMARK_ARGS% %*
    set "EXIT_CODE=%ERRORLEVEL%"
) else (
    echo [Error] No project Python found.
    echo Checked:
    echo   "%VENV_PY%"
    echo   "%DIST_PY%"
    set "EXIT_CODE=1"
)

echo.
echo Press any key to exit.
pause > nul

exit /b %EXIT_CODE%
