# Shared Color Palette

ERROR_PRINT = "#FF5252"
INPUT_PRINT = "#6BB6FF"
OUTPUT_PRINT = "#FFFFFF"

WINDOW_BG = "#1c1b1b"
TOP_BAR_BG = "#1a1919"

BUTTON_TEXT = "#FFFFFF"

BUTTON_BORDER = "#302e2e"
BUTTON_ENABLED_BORDER = "#d63c24"
BUTTON_ACTIVELY_RUNNING_BORDER = "#24d62a"

BUTTON_BG = TOP_BAR_BG
BUTTON_ENABLED_BG = TOP_BAR_BG
BUTTON_HOVER_BG = "#000000"
BUTTON_ACTIVELY_RUNNING_BG = TOP_BAR_BG

UNCLICKABLE_BUTTON_BG = "#808080"
UNCLICKABLE_BUTTON_BORDER = "#808080"

MENU_BUTTON_BG = BUTTON_BG
MENU_BUTTON_HOVER_BG = BUTTON_HOVER_BG
MENU_BUTTON_BORDER = BUTTON_BORDER

QSS = (
    "QPushButton, QToolButton {"
    "  padding: 4px 10px;"
    f"  border: 1px solid {BUTTON_BORDER};"
    "  border-radius: 6px;"
    f"  background-color: {BUTTON_BG};"
    f"  color: {BUTTON_TEXT};"
    "  font-weight: 600;"
    "}"
    "QPushButton:hover, QToolButton:hover {"
    f"  background-color: {BUTTON_HOVER_BG};"
    "}"
    "QPushButton:checked, QToolButton:checked {"
    "  background-color: transparent;"
    f"  border: 1px solid {BUTTON_ENABLED_BORDER};"
    f"  color: {BUTTON_TEXT};"
    "}"
    "QPushButton[restarting='true'], QToolButton[restarting='true'] {"
    f"  border: 1px solid {BUTTON_ACTIVELY_RUNNING_BORDER};"
    f"  color: {BUTTON_TEXT};"
    "}"
    "QPushButton:disabled, QToolButton:disabled {"
    f"  color: {UNCLICKABLE_BUTTON_BG};"
    "  text-decoration: line-through;"
    f"  border: 1px solid {UNCLICKABLE_BUTTON_BG};"
    "}"
    "QMenu::section {"
    f"  color: {BUTTON_TEXT};"
    "  font-weight: 600;"
    "  padding: 6px 12px;"
    f"  background-color: {WINDOW_BG};"
    "}"
    "QMenu::separator {"
    "  height: 1px;"
    f"  background: {BUTTON_BORDER};"
    "  margin: 4px 8px;"
    "}"
    "QMenu QPushButton, QMenu QToolButton {"
    f"  border: 1px solid {BUTTON_BORDER};"
    "  border-radius: 6px;"
    f"  background-color: {BUTTON_BG};"
    f"  color: {BUTTON_TEXT};"
    "  padding: 4px 10px;"
    "  text-align: left;"
    "  font-weight: 600;"
    "}"
    "QMenu QPushButton:hover, QMenu QToolButton:hover {"
    f"  background-color: {BUTTON_HOVER_BG};"
    "}"
    "QMenu QPushButton:checked, QMenu QToolButton:checked {"
    "  background-color: transparent;"
    f"  border: 1px solid {BUTTON_ENABLED_BORDER};"
    f"  color: {BUTTON_TEXT};"
    "}"
    "QMenu QPushButton[restarting='true'], QMenu QToolButton[restarting='true'] {"
    f"  border: 1px solid {BUTTON_ACTIVELY_RUNNING_BORDER};"
    f"  color: {BUTTON_TEXT};"
    "}"
    "QMenu QPushButton:disabled, QMenu QToolButton:disabled {"
    f"  color: {UNCLICKABLE_BUTTON_BG};"
    "  text-decoration: line-through;"
    f"  border: 1px solid {UNCLICKABLE_BUTTON_BG};"
    "}"
)
