    from backend.developer_settings import (
        always_on_top,
        close_after_crash,
        # crash_bg_color,
        # crash_tab_color,
        # crash_text_color,
        # crash_title,
        disable_maximize_button,
        disable_minimize_button,
        disable_resize,
        disable_x_button,
        # failure_bg_color,
        # failure_tab_color,
        # failure_text_color,
        # failure_title,
        flash_in_taskbar_after_crash,
        flash_in_taskbar_after_failure,
        flash_in_taskbar_after_success,
        foreground_after_crash,
        foreground_after_failure,
        foreground_after_success,
        hide_title_bar,
        highlight_window_on_first_print,
        main_script_args,
        open_script_after_crash,
        open_script_after_failure,
        print_message_after_crash,
        print_message_after_failure,
        print_message_after_success,
        start_maximized,
        # success_bg_color,
        # success_tab_color,
        # success_text_color,
        # success_title,
        supress_keyboard_interrupt,
        use_classic_terminal,
        use_free_threaded_python_if_available,
        windows_notification_after_crash,
        windows_notification_after_failure,
        windows_notification_after_success,